### ISSUE TITLE
Possible feature request

### ISSUE THREAD

**Issue by ual002** [JeremyAnsel/XwaCbmEditor#1]
This may have nothing to do with the editor, I'm just going to preface.

I was playing around with the little icon that shows up in the pilot records that denotes kills, Imptiny1.cbm

The game cuts up the vanilla icon for partial kills, but I CANNOT for the life of me figure out how when you load a new .png into the CBM editor, it tells the game its sliceable.  ANY change I make, the icon shows up, but only in places where it's whole, otherwise its not there, no slices.  Not PNG, not BMP not transparently or otherwise.  The vanilla icons seem to have a solid colored background the game edits out but I see no where to specify that in the CBM editor, could this be related?

I'm starting to think there is more info in the CBM that the editor is not making accessible to you, or that there is an undocumented format the image has to be in before you load it.

As a test I tried to replace Imptiny1.cbm, by saving EmailMon.cbm as the icon, and it actually splits that one, but I didnt extract and repackage any BMPs or PNGs to do it.  Some other cbms in that folder I tried to rename did not have the same effect.  

Any insight into this?

**Comment by ual002** [comment]
![unknown](https://user-images.githubusercontent.com/7959255/60231659-9d4e9a00-985f-11e9-81b9-78658552b8de.png)

**Comment by ual002** [comment]
No partial slices.

![image](https://user-images.githubusercontent.com/7959255/60232129-434ed400-9861-11e9-9fa8-aac2ca98febb.png)

**Comment by ual002** [comment]
A few trial and error things lead me to believe its more an issue with the properties I save the image with.

**Comment by JeremyAnsel** [comment]
I've found what causes the problem. I will fix it.
The problem is caused by the compression setting.

**Comment by JeremyAnsel** [comment]
Fixed

**Comment by ual002** [comment]
Badass.  Interested in the specifics.

**Comment by JeremyAnsel** [comment]
To fix an existing cbm file, load it and save it.

To see the details of fix, see https://github.com/JeremyAnsel/JeremyAnsel.Xwa.Cbm/commit/fdf925155f7062bb4894d6f565b8b63dac247346
I've disabled the compression when adding an image.

**Comment by ual002** [comment]
Issue resolved.
